#!/usr/bin/env python

import sys

from rqt_custom_gui.gui import CustomGUI
from rqt_gui.main import Main

plugin = 'rqt_custom_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))